### ISSUE TITLE
Plugin working only few minutes

### ISSUE THREAD

**Issue by Pawloov** [Xenomes/Domoticz-TinyTUYA-Local-Plugin#2]
Hi, i have Tuya Switch Door Contact. Plugin working only few minutes, then I've got in logs:
 2024-03-23 23:12:33.141 Error: TinyTuya: Call to function 'onCommand' failed, exception details:
2024-03-23 23:12:33.143 Error: TinyTuya: Traceback (most recent call last):
2024-03-23 23:12:33.143 Error: TinyTuya: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Local-Plugin/plugin.py", line 136, in onCommand
2024-03-23 23:12:33.143 Error: TinyTuya: _plugin.onCommand(DeviceID, Unit, Command, Level, Color)
2024-03-23 23:12:33.143 Error: TinyTuya: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Local-Plugin/plugin.py", line 95, in onCommand
2024-03-23 23:12:33.143 Error: TinyTuya: SendCommand(DeviceID, Unit, True if Command not in ['Off', 'Close'] else False, category)
2024-03-23 23:12:33.143 Error: TinyTuya: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Local-Plugin/plugin.py", line 513, in SendCommand
2024-03-23 23:12:33.143 Error: TinyTuya: tuya = tinytuya.Device(dev_id=str(ID), address=str(getConfigItem(ID, 'ip')), local_key=str(getConfigItem(ID, 'key')), version=str(getConfigItem(ID, 'version')), connection_timeout=1, connection_retry_limit=1)
2024-03-23 23:12:33.143 Error: TinyTuya: File "/usr/local/lib/python3.9/dist-packages/tinytuya/core.py", line 946, in __init__
2024-03-23 23:12:33.143 Error: TinyTuya: self.set_version(float(version))
2024-03-23 23:12:33.143 Error: TinyTuya: ValueError: could not convert string to float: '{}'

**Comment by Xenomes** [comment]
Hi, Thanks for testing! I added a True and False statement, I think it is the solution for you error.

**Comment by Pawloov** [comment]
Hi, After few minutes, when I press open button in domoticz still have:
  2024-03-29 14:30:06.145 Error: Tuya: Call to function 'onCommand' failed, exception details:
2024-03-29 14:30:06.146 Error: Tuya: Traceback (most recent call last):
2024-03-29 14:30:06.146 Error: Tuya: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Local-Plugin/plugin.py", line 142, in onCommand
2024-03-29 14:30:06.146 Error: Tuya: _plugin.onCommand(DeviceID, Unit, Command, Level, Color)
2024-03-29 14:30:06.146 Error: Tuya: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Local-Plugin/plugin.py", line 101, in onCommand
2024-03-29 14:30:06.146 Error: Tuya: SendCommand(DeviceID, Unit, True if Command not in ['Off', 'Close', False] else False, category)
2024-03-29 14:30:06.146 Error: Tuya: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Local-Plugin/plugin.py", line 525, in SendCommand
2024-03-29 14:30:06.147 Error: Tuya: tuya = tinytuya.Device(dev_id=str(ID), address=str(getConfigItem(ID, 'ip')), local_key=str(getConfigItem(ID, 'key')), version=str(getConfigItem(ID, 'version')), connection_timeout=1, connection_retry_limit=1)
2024-03-29 14:30:06.147 Error: Tuya: File "/usr/local/lib/python3.9/dist-packages/tinytuya/core.py", line 946, in __init__
2024-03-29 14:30:06.147 Error: Tuya: self.set_version(float(version))
2024-03-29 14:30:06.147 Error: Tuya: ValueError: could not convert string to float: '{}'

**Comment by Xenomes** [comment]
Can you share your devices.json? Remove any sensitive keys or information from the file.

**Comment by Pawloov** [comment]
[devices.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Local-Plugin/files/14847705/devices.json)

Without "key", "mac", "uuid": "dd","sn",
In Your's plugin is Command "Close" is not may be "Closed" ?

**Comment by Xenomes** [comment]
Could be, i changed, can you try it out?

**Comment by fielux** [comment]
Hi, same issue here (testing on version 0.3). After few mins the plugin stops working. In Domoticz log I find "Error: WiFi RF Receiver Garage: Device :bfc0e16500cadca117rpzv is Offline!" and if I click on a switch:

2024-08-07 19:06:09.759 Error: WiFi RF Receiver Garage: Call to function 'onCommand' failed, exception details:
2024-08-07 19:06:09.778 Error: WiFi RF Receiver Garage: Traceback (most recent call last):
2024-08-07 19:06:09.778 Error: WiFi RF Receiver Garage: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Local-Plugin/plugin.py", line 142, in onCommand
2024-08-07 19:06:09.778 Error: WiFi RF Receiver Garage: _plugin.onCommand(DeviceID, Unit, Command, Level, Color)
2024-08-07 19:06:09.778 Error: WiFi RF Receiver Garage: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Local-Plugin/plugin.py", line 101, in onCommand
2024-08-07 19:06:09.778 Error: WiFi RF Receiver Garage: SendCommand(DeviceID, Unit, True if Command not in ['Off', 'Closed', False] else False, category)
2024-08-07 19:06:09.778 Error: WiFi RF Receiver Garage: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Local-Plugin/plugin.py", line 525, in SendCommand
2024-08-07 19:06:09.778 Error: WiFi RF Receiver Garage: tuya = tinytuya.Device(dev_id=str(ID), address=str(getConfigItem(ID, 'ip')), local_key=str(getConfigItem(ID, 'key')), version=str(getConfigItem(ID, 'version')), connection_timeout=1, connection_retry_limit=1)
2024-08-07 19:06:09.778 Error: WiFi RF Receiver Garage: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-07 19:06:09.778 Error: WiFi RF Receiver Garage: File "/usr/local/lib/python3.11/dist-packages/tinytuya/core.py", line 902, in __init__
2024-08-07 19:06:09.779 Error: WiFi RF Receiver Garage: self.set_version(float(version))
2024-08-07 19:06:09.779 Error: WiFi RF Receiver Garage: ^^^^^^^^^^^^^^
2024-08-07 19:06:09.779 Error: WiFi RF Receiver Garage: ValueError: could not convert string to float: '{}'
2024-08-07 19:07:05.076 Error: WiFi RF Receiver Garage: Device :bfc0e16500cadca117rpzv is Offline!

[devices.json](https://github.com/user-attachments/files/16537826/devices.json)

**Comment by Xenomes** [comment]
Can you test the new push, a lot of thing changed.

**Comment by fielux** [comment]
Testing with the version downloaded this morning. 

I got the following error:

Error: WiFi RF Receiver Garage: handleThread: '2' line 356

any idea?

**Comment by Xenomes** [comment]
Sorry, i missed this post. The code is changed so line 356 is not matching.
